### ISSUE TITLE
需要一个新分支

### ISSUE THREAD

**Issue by oneLuckyman** [vooum/SUSYphe#29]
@vooum 我们需要一个新的分支用于提交一些额外的琐碎的文件和程序，我认为可以叫 dev-extend 或者 dev-trivial，这个分支与 main 分支的合并频率可能会比较高

**Comment by oneLuckyman** [comment]
@vooum 另外我还需要两个分支，一个是文档分支，一个发布目标的分支，也就是把现在的 dev-prospino 拆分成两个分支，其中发布目标的分支也需要经常合并到 main 分支

**Comment by vooum** [comment]
我觉得发任务和文档写到不同的文件里就行了，不用专门设置一个分支。分支就用于区分 稳定版和开发版，另外写代码的人，单列个分支，上传后可以在不同分支下测试，测试完成的就合并到main分支。

**Comment by vooum** [comment]
各个分支最终的归宿都是合并进main。
prospino部分开发完成了，就把dev-prospino删掉，新建dev-smodels分支

**Comment by oneLuckyman** [comment]
文档可以，其实没有很多的合并需求，但是任务发布是不是需要经常合并到 main 分支，不合并的话其他人经常收不到或者不知道 README 更新了

**Comment by vooum** [comment]
我发现Mac系统的电脑在文件夹里放了个 .DS_Store 文件，我把它加入 .ignore 里了
